import { test, expect } from '../src';

/**
 * AUTO-GENERATED by generateApiChainSpec() from a captured API sequence.
 * Every saveResponseField()/context.get() pair below was detected
 * automatically (analyzeApiChain) by matching a later call's request
 * field/URL id against an earlier call's response field - not hand-wired.
 * Fields with no detected source are left as the literal values captured
 * (genuinely user-supplied input, e.g. login credentials).
 */
test("DummyJSON: login -> user -> carts -> posts, auto-linked", async ({ apiActions }) => {
  await apiActions
    .sendRequest("POST", "https://dummyjson.com/auth/login", { "username": "emilys", "password": "emilyspass" })
    .expectStatus(200)
    .saveResponseField("id", "id");

  await apiActions
    .sendRequest("GET", () => `https://dummyjson.com/users/${apiActions.context.get("id")}`)
    .expectStatus(200)
    .saveResponseField("id", "id2");

  await apiActions
    .sendRequest("GET", () => `https://dummyjson.com/carts/user/${apiActions.context.get("id2")}`)
    .expectStatus(200)
    .saveResponseField("carts[0].id", "id3");

  await apiActions
    .sendRequest("GET", () => `https://dummyjson.com/posts/user/${apiActions.context.get("id3")}`)
    .expectStatus(200);

});
