import { test, expect } from '../src';

/**
 * AUTO-GENERATED by generateApiChainSpec() from a captured API sequence.
 * Every saveResponseField()/context.get() pair below was detected
 * automatically (analyzeApiChain) by matching a later call's request
 * field/URL id against an earlier call's response field - not hand-wired.
 * Fields with no detected source are left as the literal values captured
 * (genuinely user-supplied input, e.g. login credentials).
 *
 * Weak matches found (same field name, different value) - NOT auto-wired,
 * review manually if one of these should actually be linked:
 *   call 0 response."[0].title" -> call 4 request."title" (field "title")
 *   call 1 response."title" -> call 4 request."title" (field "title")
 *   call 0 response."[0].body" -> call 4 request."body" (field "body")
 *   call 1 response."body" -> call 4 request."body" (field "body")
 *   call 2 response."[0].body" -> call 4 request."body" (field "body")
 *   call 3 response."[0].body" -> call 4 request."body" (field "body")
 *   call 4 response."id" -> call 5 request."id" (field "id")
 *   call 0 response."[0].title" -> call 5 request."title" (field "title")
 *   call 1 response."title" -> call 5 request."title" (field "title")
 *   call 0 response."[0].body" -> call 5 request."body" (field "body")
 *   call 1 response."body" -> call 5 request."body" (field "body")
 *   call 2 response."[0].body" -> call 5 request."body" (field "body")
 *   call 3 response."[0].body" -> call 5 request."body" (field "body")
 *   call 4 response."id" -> call 5 request."$url:4" (field "id")
 *   call 0 response."[0].title" -> call 6 request."title" (field "title")
 *   call 1 response."title" -> call 6 request."title" (field "title")
 *   call 4 response."title" -> call 6 request."title" (field "title")
 *   call 5 response."title" -> call 6 request."title" (field "title")
 *   call 4 response."id" -> call 6 request."$url:4" (field "id")
 *   call 4 response."id" -> call 7 request."$url:4" (field "id")
 */
test("JSONPlaceholder: posts/comments chain, auto-linked (path + query)", async ({ apiActions }) => {
  await apiActions
    .sendRequest("GET", "https://jsonplaceholder.typicode.com/posts")
    .expectStatus(200)
    .saveResponseField("[0].id", "id")
    .saveResponseField("[0].userId", "userId");

  await apiActions
    .sendRequest("GET", () => `https://jsonplaceholder.typicode.com/posts/${apiActions.context.get("id")}`)
    .expectStatus(200)
    .saveResponseField("id", "id2")
    .saveResponseField("userId", "userId2");

  await apiActions
    .sendRequest("GET", () => `https://jsonplaceholder.typicode.com/posts/${apiActions.context.get("id2")}/comments`)
    .expectStatus(200)
    .saveResponseField("[0].postId", "postId")
    .saveResponseField("[0].id", "id3");

  await apiActions
    .sendRequest("GET", () => `https://jsonplaceholder.typicode.com/comments?postId=${apiActions.context.get("postId")}`)
    .expectStatus(200)
    .saveResponseField("[0].id", "id4");

  await apiActions
    .sendRequest("POST", "https://jsonplaceholder.typicode.com/posts", { "title": "foo", "body": "bar", "userId": apiActions.context.get("userId2") })
    .expectStatus(201)
    .saveResponseField("title", "title")
    .saveResponseField("body", "body")
    .saveResponseField("userId", "userId3");

  await apiActions
    .sendRequest("PUT", () => `https://jsonplaceholder.typicode.com/posts/${apiActions.context.get("id4")}`, { "id": apiActions.context.get("id4"), "title": apiActions.context.get("title"), "body": apiActions.context.get("body"), "userId": apiActions.context.get("userId3") })
    .expectStatus(200)
    .saveResponseField("id", "id5");

  await apiActions
    .sendRequest("PATCH", () => `https://jsonplaceholder.typicode.com/posts/${apiActions.context.get("id5")}`, { "title": "patched title" })
    .expectStatus(200)
    .saveResponseField("id", "id6");

  await apiActions
    .sendRequest("DELETE", () => `https://jsonplaceholder.typicode.com/posts/${apiActions.context.get("id6")}`)
    .expectStatus(200);

});
