import { test, expect } from '../src';

/**
 * AUTO-GENERATED by generateApiChainSpec() from a captured API sequence.
 * Every saveResponseField()/context.get() pair below was detected
 * automatically (analyzeApiChain) by matching a later call's request
 * field/URL id against an earlier call's response field - not hand-wired.
 * Fields with no detected source are left as the literal values captured
 * (genuinely user-supplied input, e.g. login credentials).
 *
 * Weak matches found (same field name, different value) - NOT auto-wired,
 * review manually if one of these should actually be linked:
 *   call 0 response."user.id" -> call 2 request."$url:4" (field "id")
 *   call 0 response."user.id" -> call 3 request."$url:4" (field "id")
 */
test("Customer Billing: login -> entries -> customer -> customer entries, auto-linked", async ({ apiActions }) => {
  await apiActions
    .sendRequest("POST", "https://customer-billing-dev.vercel.app/auth/login", { "email": "surya@evanke.com", "password": "Test@123" })
    .expectStatus(200);

  await apiActions
    .sendRequest("GET", "https://customer-billing-dev.vercel.app/customers/entries/all?status=active")
    .expectStatus(200)
    .saveResponseField("[0].id", "id");

  await apiActions
    .sendRequest("GET", () => `https://customer-billing-dev.vercel.app/customers/${apiActions.context.get("id")}`)
    .expectStatus(200)
    .saveResponseField("id", "id2");

  await apiActions
    .sendRequest("GET", () => `https://customer-billing-dev.vercel.app/customers/${apiActions.context.get("id2")}/entries`)
    .expectStatus(200);

});
