
export const testRunConstants = {
    DEFAULT_TIMEOUT_IN_MILLISECONDS : 30000,  // element wait
    CUCUMBER_PROMISE_TIMEOUT: 150000, // ensure to be greater than DEFAULT_TIMEOUT_IN_MILLISECONDS
    DEFAULT_ELEMENT_FINDER_RETRIES: 2,
    DEFAULT_ELEMENT_PROPERTY_FAILURE_RETRY: 2,
    DEFAULT_ACTION_WAIT: 5000
   };
