/**
 * Scans every locator YAML/JSON file in a consumer project
 * (e2e/locators/generated/**, e2e/locators/common.yaml) and writes a
 * `LocatorName` union type covering every known name, so element-name
 * arguments (webActions.fill(name, ...), .click(name), etc.) can be checked
 * against real locator names instead of a bare `string` — typos become a
 * type error instead of a runtime "did you mean...?" warning.
 *
 * Run via `npx playwright-without-bdd-generate-types` (see
 * scripts/generate-locator-types.js) after adding/renaming locator YAML
 * entries, or call this function directly from a setup script.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { CATEGORIES, LOCATOR_ROOT } from '../locators/locatorPaths';

function collectNamesFromFile(fp: string): string[] {
  try {
    const raw = fs.readFileSync(fp, 'utf8');
    const doc = fp.endsWith('.json') ? JSON.parse(raw) : yaml.load(raw);
    if (!doc || typeof doc !== 'object' || Array.isArray(doc)) return [];
    return Object.keys(doc as Record<string, unknown>);
  } catch {
    return [];
  }
}

function walk(dir: string, files: string[]): void {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, files);
    else if (entry.name.endsWith('.yaml') || entry.name.endsWith('.json')) files.push(full);
  }
}

function collectAllLocatorFiles(): string[] {
  const files: string[] = [];
  for (const cat of CATEGORIES) walk(path.join(LOCATOR_ROOT, cat), files);
  const commonFile = path.resolve(LOCATOR_ROOT, '..', 'common.yaml');
  if (fs.existsSync(commonFile)) files.push(commonFile);
  return files;
}

/** Writes a `LocatorName` union type file covering every name in every loaded locator YAML/JSON. Returns the file written and the names found. */
export function generateLocatorTypes(outFile = path.join(LOCATOR_ROOT, 'locator-names.d.ts')): { outFile: string; names: string[] } {
  const names = new Set<string>();
  for (const fp of collectAllLocatorFiles()) {
    for (const name of collectNamesFromFile(fp)) names.add(name);
  }
  const sorted = [...names].sort();
  const union = sorted.length > 0 ? sorted.map((n) => `  | ${JSON.stringify(n)}`).join('\n') : '  | never';
  const content =
    `// Auto-generated by playwright-without-bdd-library's locator-name codegen. Do not edit by hand -\n` +
    `// re-run \`npx playwright-without-bdd-generate-types\` after changing locator YAML files.\n` +
    `export type LocatorName =\n${union};\n`;
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, content, 'utf8');
  return { outFile, names: sorted };
}
