import type { Config } from "tailwindcss";

// Token names match the "Kinetic Syntax" / DevTest AI reference design (see
// the Stitch mockups this was matched against) exactly, but values are now
// CSS variables (defined per-theme in globals.css) instead of literal hex,
// so next-themes can swap the whole palette between light/dark/system by
// just toggling a class on <html> - no component ever needs a `dark:` prefix.
export default {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "var(--on-primary-fixed)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "on-primary-container": "var(--on-primary-container)",
        "on-secondary": "var(--on-secondary)",
        "surface-container-high": "var(--surface-container-high)",
        "on-primary": "var(--on-primary)",
        "surface-bright": "var(--surface-bright)",
        "primary-container": "var(--primary-container)",
        primary: "var(--primary)",
        "outline-variant": "var(--outline-variant)",
        "surface-variant": "var(--surface-variant)",
        "on-error": "var(--on-error)",
        "secondary-fixed": "var(--secondary-fixed)",
        secondary: "var(--secondary)",
        "on-background": "var(--on-background)",
        "on-error-container": "var(--on-error-container)",
        background: "var(--background)",
        "on-surface-variant": "var(--on-surface-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-surface": "var(--on-surface)",
        outline: "var(--outline)",
        surface: "var(--surface)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-dim": "var(--surface-dim)",
        "tertiary-container": "var(--tertiary-container)",
        tertiary: "var(--tertiary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-tint": "var(--surface-tint)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        error: "var(--error)",
        "inverse-surface": "var(--inverse-surface)",
        "secondary-container": "var(--secondary-container)",
        "error-container": "var(--error-container)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary": "var(--on-tertiary)",
        "surface-container": "var(--surface-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        // Not part of the M3 token set, but used by the reference for
        // terminal/log line coloring (execution logs, status dots) - kept
        // as their own literal names rather than overloading tertiary/error.
        "log-success": "var(--log-success)",
        "log-warning": "var(--log-warning)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sidebar_width: "260px",
        gutter: "16px",
        unit: "4px",
        lg: "24px",
        md: "16px",
        xl: "32px",
        topbar_height: "56px",
        xs: "4px",
        margin: "24px",
        sm: "8px",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "code-sm": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "code-md": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "display-lg": ["var(--font-geist)", "Geist", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-geist)", "Geist", "sans-serif"],
        "headline-sm": ["var(--font-geist)", "Geist", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-sm": ["12px", { lineHeight: "1.5", fontWeight: "400" }],
        "code-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "1.4", fontWeight: "500" }],
      },
      keyframes: {
        "fade-in": { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
      animation: {
        "fade-in": "fade-in 0.3s ease-out",
      },
    },
  },
  plugins: [],
} satisfies Config;
